FROM nginx:latest

# Copiar a configuração personalizada
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Copiar os arquivos HTML
COPY . /usr/share/nginx/html

EXPOSE 8888

CMD ["nginx", "-g", "daemon off;"]
